apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
  namespace: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pacman      
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: docker.io/theonlyhero/pacman-modern6:latest
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
        env:
          - name: MONGO_URL
            value: "mongodb://mongo.mongo.svc.cluster.local:27017/pacman?retryWrites=false"
          - name: MONGO_SERVICE_HOST
            value: mongo.mongo.svc.cluster.local
          - name: MONGO_SERVICE_PORT
            value: "27017"
              #- name: METRICS_DEBUG
            #value: "1"
